[package]
name = "dns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bloomfilter = "1.0"
crossbeam-channel = "0.5"
simple-dns = "0.7"
socket2 = "0.5"
tikv-jemallocator = "0.5"
tokio = { version = "1", features = ["full"] }
toml = { version = "0.8", features = ["preserve_order"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
