[package]
name = "dns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
simple-dns = { git = "https://github.com/masmullin2000/simple-dns.git", branch = "access_data" }
socket2 = "0.5"
tokio = { version = "1", features = ["full"] }
toml = { version = "0.8", features = ["preserve_order"] }
trie-rs = "0.4.0"

exists_map = { git = "https://github.com/masmullin2000/exists_map.git" }

[profile.release]
lto = true
codegen-units = 1
strip = true
